steps:
  # 1. Build the Frontend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_DIRECTUS_URL=http://34.100.194.88:8055'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/portfolio/frontend:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/portfolio/frontend:latest'
      - '.'
    id: 'build-frontend'

  # 2. Push the Frontend Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/portfolio/frontend'
    id: 'push-frontend'



  # 3. Deploy App to Compute Engine (VM)
  # Ensure the Cloud Build service account has the necessary IAM permissions and SSH keys
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Securely copy the Compose file to the VM
        gcloud compute scp docker-compose.prod.yml portfolio-vm:/opt/hannah-portfolio/ --zone=asia-south1-a --quiet
        
        # SSH in to pull the new images and restart the containers
        gcloud compute ssh portfolio-vm --zone=asia-south1-a --quiet --command="sudo bash -c 'cd /opt/hannah-portfolio && gcloud auth configure-docker asia-south1-docker.pkg.dev --quiet && docker compose -f docker-compose.prod.yml pull && docker compose -f docker-compose.prod.yml up -d'"
    id: 'deploy-vm'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/portfolio/frontend:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/portfolio/frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
